name: Pull Request Check

on:
  pull_request:
  push:
    branchs:
      - master

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go
      - uses: actions/checkout@v2
      - run: go mod download
      - run: go build -v ./...
      - run: |
          go get -u golang.org/x/lint/golint
          golint ./...
      - run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
      - run: bash <(curl -s https://codecov.io/bash)
