name: Send invitations

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
        id: go
      - uses: actions/checkout@v2
      - run: go mod download
      - run: go build -v .
      - env:
          TOKEN: ${{ secrets.GH_TOKEN }}
        run: ./members -t "$TOKEN" update
